# Generated by Django 2.2 on 2022-01-03 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest_track_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_notes', to='quest_track_app.Task'),
        ),
    ]
