# Generated by Django 4.0.6 on 2023-07-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_track_app', '0004_complete_status_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee'), ('head', 'Head'), ('executive', 'Executive')], max_length=20),
        ),
    ]
