# Generated by Django 4.0.6 on 2023-07-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_track_app', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
