# Generated by Django 4.0.6 on 2023-07-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest_track_app', '0006_user_secret_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest_track_app.user'),
        ),
    ]
